---
- name: update apt repositories
  apt: update_cache=yes

- name: upgrade distribution
  apt: upgrade=dist
  notify:
    - generate locales
    - reconfigure locale for installed packages
  tags:
    - production_only
